### ISSUE TITLE
Support for apple m1

### ISSUE THREAD

**Issue by DingkunLiu** [Eelbrain/Eelbrain#41]
Could you provide an arm64 wheel on conda?

**Comment by christianbrodbeck** [comment]
Looking at [this](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/), I think this will only be possible once the dependencies become available, in particular `mayavi` is not even on the [list](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt) yet. I could make `mayavi` a soft dependency that needs to be installed separately, but [wxPython](https://anaconda.org/conda-forge/wxpython) does not seem to be built either. 

Do you need any of the GUI functionality from Eelbrain (without it you could still make plots in notebooks, just not of pysurfer brains)? If not I would suggest using a trimmed-down environment (I'll help with that) and then installing Eelbrain from PYPI so it's compiled locally (I don't have an arm64 platform to test that though).

**Comment by DingkunLiu** [comment]
Thank you for your reply. Yeah, I usually work without GUI, so a console-only version is fine. I can test the built wheel. Otherwise, you can give me some instructions on how to build it on my own.

**Comment by christianbrodbeck** [comment]
My suggestion would be to start with [this environment](https://github.com/christianbrodbeck/Eelbrain/blob/r/0.34/env-dev.yml) and remove libraries that are not available on conda-forge yet (I think that's at least mayavi/vtk, and pysurfer which needs mayavi). Then install eelbrain with pip, and hope that it compiles :)  . Then see if you get any import errors, and we can see whether those can be made into soft dependencies.

**Comment by christianbrodbeck** [comment]
Native `osx-arm64` build is now on conda-forge.
