### ISSUE TITLE
Loading CND format dataset with load.cnd

### ISSUE THREAD

**Issue by xinyiguan** [Eelbrain/Eelbrain#43]
Hi, 

I was trying to load the EEG data from the diliBach CND dataset (the dataset from the CNSP 2021 Workshop):
```
import eelbrain

eeg_data = eelbrain.load.cnd('/Users/Datasets/diliBach/dataCND/dataSub1.mat')
```

and I encountered this error message:

``` 
raise ValueError(f"Can not assign item to Dataset. The item`s length {n} is different from the number of cases in the Dataset {self.n_cases}.")
ValueError: Can not assign item to Dataset. The item`s length 0 is different from the number of cases in the Dataset 30.
```
I also tried with the CND format of **LalorNatSpeech** dataset, and seemed to work fine.

As far as I understand, the **diliBach** is in the CND data-format, thus `eelbrain.load.cnd` should work.

Is this a problem with diliBach dataset in CND format? I see that in mat files in diliBach, the `origTrialPosition ` is an empty list. Is that the problem for the error?

**Comment by christianbrodbeck** [comment]
Hi @xinyiguan, I contacted Giovanni Di Liberto about what the desired behavior should be if `origTrialPosition` is missing.

**Comment by christianbrodbeck** [comment]
I haven't heard back yet, can you maybe tell from the data what should happen? Can you do the analysis without `origTrialPosition`, so that it would be okay to just drop it?

**Comment by xinyiguan** [comment]
I resolved this by adding the `origTrialPosition` values myself. Thanks for stepping in!

**Comment by christianbrodbeck** [comment]
Great! @diliberg commented

> that variable should not be empty. That is an issue with the dataset. I did that quickly for the workshop, I am afraid, and I forgot to fix it as it was not important. 
>
> In brief. Let me give you two examples:
> 1) audio-book listening experiment. The trial order was the same for all participants (as the order was important. So, origTrialPosition should be 1:nTrials.
> 2) Bach melody listening. The trial order was randomised -> different for different participants. So, when building the CND file, the approach I used was to sort everything according to a particular order (audio 1, audio 2, etc), so that trial 1 corresponded to audio 1 for all participants.  origTrialPositionis a variable that allows us to remember in which order that trial was actually played for a given subject. I'll fix that when I have some time, but that should not be a problem (exactly because the order was randomised).

So from the next Eelbrain release there will just be a warning.
