### ISSUE TITLE
Trouble adding NDVar to brain plot

### ISSUE THREAD

**Issue by jj3479** [Eelbrain/Eelbrain#44]
Hi,

I'm trying to add NDVar data to a brain plot, but I keep getting the error shown below. It was my understanding that if there is a case dimension of an NDVar, data would be averaged over cases, but the error is saying the NDVar must be one or two dimensional... 

```
b = e.plot.brain.brain('fsaverage', hemi = 'lh', surf = 'white', subjects_dir=subjects_dir,
                  background='white', cortex='low_contrast',views=['lat'])

b.add_label(label = 'BA11', color='#F7B4AE', alpha=1, scalar_thresh=None, borders=False, hemi='lh')

b.add_ndvar(data, cmap=None, vmin=None, vmax=None, smoothing_steps=None, colorbar=False, time_label='ms',
            lighting=False, contours=True, alpha=1, remove_existing=False)

ValueError: <NDVar 'src': 54 case, 58 source, 501 time>: must be one- or two dimensional`
```

**Comment by christianbrodbeck** [comment]
This is generally the case but not for brain plots. Just use `data.mean(‘case’)`. I don’t remember whether there is a specific reason for not doing it automatically here, I will check.

**Comment by jj3479** [comment]
yay thanks!

**Comment by christianbrodbeck** [comment]
I think the reason is that a `case x source` NDVar would be ambiguous as to whether you want to average the cases or treat case as the second axis so you can flip through case with the arrow keys. I’ll add a note to the docs.
