### ISSUE TITLE
Adding parcellation to vol source space

### ISSUE THREAD

**Issue by reispat** [Eelbrain/Eelbrain#46]
Hi,

I wanted to add a parcellation to a volume source space with 3D vectors (`stc_nd` is a `VolVectorSourceEstimate`):

```
meg_source_combined = eb.load.fiff.stc_ndvar(stc_nd, src='vol-7', subject='fsaverage', subjects_dir=mri_path,
                                                     method='MNE', fixed=False, parc='aparc+aseg')
```

In `eelbrain.load.fiff.stc_ndvar`, the NDVar is constructed here (line 1438 in fiff.py):
```
 # Construct NDVar Dimensions
    time = UTS(stc.tmin, stc.tstep, stc.times.size)
    if isinstance(stc, MNE_VOLUME_STC):
        ss = VolumeSourceSpace(vertices, subject, src, subjects_dir, None, filename=sss_filename)
        is_vector = stc.data.ndim == 3
    elif isinstance(stc, (mne.SourceEstimate, mne.VectorSourceEstimate)):
        ss = SourceSpace(vertices, subject, src, subjects_dir, parc, filename=sss_filename)
        is_vector = isinstance(stc, mne.VectorSourceEstimate)
```
Due to the `None` when constructing `VolumeSourceSpace`, `parc='aparc+aseg'` is ignored. In the documentation of [eelbrain.VolumeSourceSpace](https://eelbrain.readthedocs.io/en/stable/generated/eelbrain.VolumeSourceSpace.html) you write that parc "Only applies to ico source spaces, default is ‘aparc’.". Is there a specific reason why it is not implemented for e.g. `vol-7` source spaces?

Thank you! Best, Patrick

**Comment by christianbrodbeck** [comment]
Hi Patrick, it looks like when I implemented parcellations for volume source spaces I did not update the `load.fiff.stc_ndvar` constructor. I fixed it in master and will make an update on conda-forge soon.

**Comment by reispat** [comment]
Hi Christian, perfect, thank you for the very fast fix!
