### ISSUE TITLE
Boosting residual defined for individual eeg channels, but documentation states otherwise. 

### ISSUE THREAD

**Issue by iranroman** [Eelbrain/Eelbrain#47]
The `eelbrain.BoostingResult` documentation says that the` residual error='l2': the sum of the squared differences between y and h * x.`

However, when I print the residual, I get a value for each eeg channel (64 channels in my case; biosemi64). This is confusing, as based on the documentation I was expecting a single value, not 64.

**Comment by christianbrodbeck** [comment]
When you have multiple dependent variables `boosting` assumes a mass-univariate approach. I've tried to clarify this in the [documentation for `y`](https://github.com/christianbrodbeck/Eelbrain/commit/04bbb1e9f09f17299477d7f6e879912544f0e912).  Please feel free to improve on this if you see more ways to make it clearer :)
