### ISSUE TITLE
How should I import my meg raw file into eelbrain's NDVar format?

### ISSUE THREAD

**Issue by hasibagen** [Eelbrain/Eelbrain#54]
My data is meg data from MEGIN/Elekta Neuromag VectorView and TRIUX in .fif format.
I have 8 stories, one raw file for each story, which I have pre-processed with mne and saved as fif format files.

The issues I have encountered at the moment are

1: meg's fif format does not have montage. and ds['epochs'] = load.fif.epochs(ds) gives an error
ValueError: 'MEG0111' is not in list. seems to be because of montage problem with meg.

```
Traceback (most recent call last).
  File "/Users//opt/anaconda3/envs/mne/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-d2f9910b3bf8>", line 1, in <module>
    ep = eelbrain.load.fiff.add_epochs(ds)
  File "/Users//opt/anaconda3/envs/mne/lib/python3.10/site-packages/eelbrain/_io/fiff.py", line 570, in add_epochs
    ds[name] = epochs_ndvar(epochs_, name, data, mult=mult, info=info.
  File "/Users//opt/anaconda3/envs/mne/lib/python3.10/site-packages/eelbrain/_io/fiff.py", line 1151, in epochs_ndvar
    sensor = sensors or sensor_dim(epochs, picks, sysname, connectivity)
  File "/Users//opt/anaconda3/envs/mne/lib/python3.10/site-packages/eelbrain/_io/fiff.py", line 822, in sensor_dim
    index = np.array([names.index(name) for name in ch_names])
  File "/Users//opt/anaconda3/envs/mne/lib/python3.10/site-packages/eelbrain/_io/fiff.py", line 822, in <listcomp>
    index = np.array([names.index(name) for name in ch_names])
```

I have tried asking this question in the mne forum and the developer in question suggested that I use layout, but it seems that layout does not import well into eelbrain's data structure.

https://mne.discourse.group/t/how-to-get-fif-montage-with-channel/6711

I tried building senosr by myself, but it seems that eelbrain's sensors are 3D arrays, but meg's channels are 4D arrays.

```
raw = raw = mne.io.read_raw_fif(file_path)
raw = raw.pick_types(meg=True, eeg=False, eog=False)
from mne.channels import read_layout
layout = read_layout("Vectorview-all")
meg_senor = eelbrain.Sensor(locs=layout.pos、
                      names=raw.info.ch_names、
                      sysname="fif")
report:
Traceback (most recent call last):
  File "/Users/hasibagen/opt/anaconda3/envs/mne/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-502433b3dc2d>", line 1, in <module>
    sen = eelbrain.Sensor(locs=layout.pos,
  File "/Users/hasibagen/opt/anaconda3/envs/mne/lib/python3.10/site-packages/eelbrain/_data_obj.py", line 8942, in __init__
    raise ValueError(f"locs needs to have shape (n_sensors, 3), got {locs.shape=}")
ValueError: locs needs to have shape (n_sensors, 3), got locs.shape=(306, 4)
```

2: eelbrain does not have the ability to import raw format as NDVar directly. I would like to use mne to process all the raw data and import it into eelbrain, because my data is special, each story is a separate fif, and the length is different.

This is the code I use to pre-process the raw files:
```
raw = mne.io.read_raw_fif(file_path)  
raw.load_data()  
meg_picks = mne.pick_types(raw.info, meg=True)  
freqs = (60, 180)  
raw_notch = raw.copy().notch_filter(freqs=freqs, picks=meg_picks, n_jobs=6)  
raw_filter = raw_notch.copy().filter(l_freq=1, h_freq=15, picks=meg_picks, n_jobs=6)  
events = mne.find_events(raw, stim_channel='STI101',uint_cast = True)  
events = mne.pick_events(events, include=32)  
marker_time = (events[0, 0] - raw_filter.first_samp) / raw.info['sfreq']  
dely_time = all_start.iloc[sub - 1, story - 1] / raw.info['sfreq']  
time_min = marker_time + dely_time  
time_max = time_min + all_duration.iloc[story-1][0] + 10  
raw_cut = raw_filter.copy().crop(tmin=time_min, tmax=time_max)  
raw_downsampled = raw_cut.copy().resample(sfreq=100)
```

mne: 1.3.1
Eelbrain :0.38
ubuntu:20.04

**Comment by christianbrodbeck** [comment]
It looks like the error occurs when trying to automatically determine the sensor connectivity (=adjacency). If you don't need this you can set it to `'none'`. If you need it then you'd need to either figure out how MNE-Python can provide it and use that as `connectivity` argument, or you can initialize the `NDVar` without connectivity and then add it using `ndvar.sensor.set_connectivity`

By the way you can import mne `Raw` objects using `load.fiff.raw_ndvar`, I realize this is missing from the docs and will add it.

Also, since it looks like right now the automatic function fails, if you can share a small data snippet I could look into why.

**Comment by hasibagen** [comment]
> It looks like the error occurs when trying to automatically determine the sensor connectivity (=adjacency). If you don't need this you can set it to `'none'`. If you need it then you'd need to either figure out how MNE-Python can provide it and use that as `connectivity` argument, or you can initialize the `NDVar` without connectivity and then add it using `ndvar.sensor.set_connectivity`
> 
> By the way you can import mne `Raw` objects using `load.fiff.raw_ndvar`, I realize this is missing from the docs and will add it.
> 
> Also, since it looks like right now the automatic function fails, if you can share a small data snippet I could look into why.


Sorry for my late reply.
I'm not a programming expert, just a psychology student, and after your reply, I tried my best to find a solution.
At present, ValueError: 'MEG0111' is not in list. This problem still exists. I saw your suggestion to change the connectivity to none, and I did the same, but this error will still be reported.
I tried the following code

```
raw_eel = load.fiff.raw_ndvar(raw, sysname='neuromag306', connectivity= None)
raw_eel = load.fiff.raw_ndvar(raw, sysname=None, connectivity=None)
epoch_eel = eelbrain.load.fiff.epochs_ndvar(epochs = epoch, connectivity= None)
```

The result will report ValueError: 'MEG0111' is not in list. I sent my data to you via email, thank you for checking it.

The way I am currently trying to convert mne data into eelbrain ndvar data is the following code, but this does not seem very convenient. I hope to fix this bug and directly import mne raw fif to eelbrain.

```

# create the time dimension
fs = 100
tstep = 1/fs
time = eelbrain.UTS(0, tstep, len(envelope_data[0,0].flatten()))
envelope = NDVar(envelope_data[0,0].flatten(), (time), name='envelope')
  
# sensor dim
sensor = eelbrain.load.fiff.sensor_dim(raw)
# raw data
raw_data = raw. get_data()
raw_data = raw_data[:, :len(envelope_data[0,0].flatten())].T
meg = eelbrain.NDVar(raw_data, (time,sensor), name='MEG')
  
res = boosting(meg, envelope, 0, 0.500, basis=0.100, partitions=4)
```

**Comment by christianbrodbeck** [comment]
Can you try again with the most recent version (0.39)?

You should be able to use [load.mne.raw_ndvar](https://eelbrain.readthedocs.io/en/stable/generated/generated/eelbrain.load.mne.raw_ndvar.html#eelbrain.load.mne.raw_ndvar):
```
ndvar = eelbrain.load.mne.raw_ndvar(raw)
```

**Comment by hasibagen** [comment]
> 

@christianbrodbeck 

Sorry I didn't see this reply before, I just saw it and have updated eelbrain to 0.39.
```
conda list eelbrain
# packages in environment at mne.
# Name Version Build Channel
eelbrain 0.39 py310h654ee6d_0 conda-forge

```
But it still reports ValueError: 'MEG0111' is not in list
```
raw = mne.io.read_raw_fif(file_path)
ndvar = eelbrain.load.mne.raw_ndvar(raw)
```

**Comment by christianbrodbeck** [comment]
It looks like your channel names are different from the FIFF files in MNE-Python (`MEG0111` instead of `MEG 0111`), do you know why that might be? Are there different standards depending on location?

For now, you can import your data by renaming your channels:

```
names = {name: f'{name[:3]} {name[3:]}' for name in raw.ch_names if name.startswith('MEG')}
raw = raw.rename_channels(names)
ndvar = load.mne.raw_ndvar(raw)
```

**Comment by hasibagen** [comment]
> It looks like your channel names are different from the FIFF files in MNE-Python (`MEG0111` instead of `MEG 0111`), do you know why that might be? Are there different standards depending on location?
> 
> For now, you can import your data by renaming your channels:
> 
> ```
> names = {name: f'{name[:3]} {name[3:]}' for name in raw.ch_names if name.startswith('MEG')}
> raw = raw.rename_channels(names)
> ndvar = load.mne.raw_ndvar(raw)
> ```

Thank you very much for your help.
I did miss the space detail here in the channel name, I will try to find out why this is happening.
For now, I will follow this code to import mne raw fif to eelbrain.

Many thanks!

**Comment by hasibagen** [comment]
There is one more detail about this, I would like to ask how to import 306 channels if I want to import them together? It seems that when load.mne.raw_ndvar selects data, it must be some of the following, and if it is none, it seems to be 102 mag channels automatically.
(needs to be one of: eeg, eog, mag, grad, planar1, planar2)

@christianbrodbeck

**Comment by christianbrodbeck** [comment]
This is currently not possible in a single `NDVar`. Since the different sensor types have different properties, how would you expect the combined `NDVar` to behave (e.g. for topo-plots, cluster-based tests etc.)? If different sensor types cover the same spacial locations, and it is possible to consider different sensor types to constitute components of a vector, then sensors could be stacked, e.g. using a `Space` dimension. Maybe what you're looking for could be achieved with source localization, which maps the different sensor types to a single representational data type?

**Comment by hasibagen** [comment]
> This is currently not possible in a single `NDVar`. Since the different sensor types have different properties, how would you expect the combined `NDVar` to behave (e.g. for topo-plots, cluster-based tests etc.)? If different sensor types cover the same spacial locations, and it is possible to consider different sensor types to constitute components of a vector, then sensors could be stacked, e.g. using a `Space` dimension. Maybe what you're looking for could be achieved with source localization, which maps the different sensor types to a single representational data type?

Thank you very much indeed for your answer.
I probably understand what you mean, you think that because different sensors have different properties, they can't be used at the same time and exist in one ndvar at the same time.
I understood that part.
I was raising this question because I saw some papers doing mtrf that used meg data with all types of meg channels of 306 at the same time. And when I do my own mtrf modeling, it seems that there is not much difference between the different types.

**Comment by christianbrodbeck** [comment]
In that case I would just call the `boosting` function separately for the different sensor types. Sensor space mTRFs are estimated in parallel anyways (the signal at one sensor does not influences the mTRF at other sensors), and you will also have to plot them separately.

**Comment by hasibagen** [comment]
> In that case I would just call the `boosting` function separately for the different sensor types. Sensor space mTRFs are estimated in parallel anyways (the signal at one sensor does not influences the mTRF at other sensors), and you will also have to plot them separately.

I understand, I will refer to your suggestion for data analysis.
