### ISSUE TITLE
Having a dead kernel each time I run eelbrain on my data

### ISSUE THREAD

**Issue by gurasog** [Eelbrain/Eelbrain#59]
Hi! Thanks fo amazing research tool! I am trying to use it to do my research in electrophysiology.

I am using eelbrain to work with MEG data. The data is big; it consists of 204 channels with a sampling frequency at 1000Hz.  When I started to run `eelbrain.boosting() `  I got  a dead kernel, and I was getting it each time I run this function.

 I decided to decrease the number of channels and sampling frequency now my  NDVarX is `<NDVar: 1 case, 7500 time, 5 sensor> `and NDVarY is just `<NDVar: 1 case, 7500 time>`, but the dead kernels was till there when I run `eelbrain.boosting() `

Finally, I decided to launch the script on a server to be sure that computational capacity is enough, but the kernel was dead again. 

Did anybody experience such an issue? I would be thankful if anybody can help me!
I use eelbrain 0.39

**Comment by christianbrodbeck** [comment]
Can you run this in an iPython terminal and see if you get any error message?

**Comment by christianbrodbeck** [comment]
The boosting algorithm itself runs in C, is it possible it looks like a dead kernel to Jupyter when it's in fact still running? Can you check your Activity Monitor to see whether Python is still using your CPU?

**Comment by gurasog** [comment]
Thanks for your recommendations!

Yes, it is crushing in command line too
```
>>> eelbrain.boosting(NDVar_y, NDVar_x, tstart=0, tstop=epochs_np_long.shape[1])
Segmentation fault (core dumped)
```

I also checked the Activity Monitor right after Jupyter kernel death, and there are some processes related to python, but I don't think they are coming from eelbrain. I believe that those are from Jupyter server itself which is not dead.

**Comment by christianbrodbeck** [comment]
What is epochs_np_long.shape[1]?

**Comment by gurasog** [comment]
It just equals to 7500, since I have a NDVar of length 7500

**Comment by christianbrodbeck** [comment]
tstop is in seconds and should be << than the length of y

**Comment by christianbrodbeck** [comment]
I've added a check to make sure the kernel is not longer than the data segments in Eelbrain 0.39.7. Feel free to reopen or open a new issue if the problem persists even with appropriate kernel lengths.
