### ISSUE TITLE
Under-utilization of CPU on M1 Ultra during boosting

### ISSUE THREAD

**Issue by christianbrodbeck** [Eelbrain/Eelbrain#61]
Even though 20 threads are created, CPU utilization does not exceed 1000% with usually total CPU usage >50% idle

Seems to be a deeper issue affecting OpenMP in general:
- https://github.com/llvm/llvm-project/issues/62554
- https://github.com/dmlc/xgboost/issues/8320

**Comment by kaizenjinco** [comment]
The problem still present to me in XGBoost 2.0.3. Maybe a lot of work will be put on OpenMP

**Comment by christianbrodbeck** [comment]
M2 Ultra does not seem to have this issue, uses >2000%

**Comment by christianbrodbeck** [comment]
Closing this as it seems fixed (at least on M2)
