### ISSUE TITLE
Eelbrain doesn't lauch after update

### ISSUE THREAD

**Issue by aristia** [Eelbrain/Eelbrain#62]
Hey, 
I updated eelbrain to the latest version as the last version I had was from last year. After updating I cannot launch eelbrain 
![Capture d'écran 2023-12-05 142419](https://github.com/christianbrodbeck/Eelbrain/assets/13418371/cdeac35d-94e0-4acb-b86e-df1e9f17d3d1)

I tried to downgrade mne to version 1.5, but it doesn't work.

**Comment by christianbrodbeck** [comment]
This is due to a change in mne-Python 1.6 that broke backwards compatibility, so downgrading to mne 1.5 should work. If this is causing trouble you could also try the current alpha version of Eelbrain, 0.40a6. I will release a fix for 0.39 soon.

**Comment by aristia** [comment]
I did downgrade it to mne 1.5 but didn't work.. the alpha version works though there are warning related to mne 1.6
Thanks @christianbrodbeck !

**Comment by christianbrodbeck** [comment]
Should also be fixed now in Eelbrain 0.39.9 which should appear on conda-forge shortly

**Comment by christianbrodbeck** [comment]
> I did downgrade it to mne 1.5 but didn't work.. the alpha version works though there are warning related to mne 1.6 Thanks @christianbrodbeck !

What are the warnings you see?

**Comment by aristia** [comment]
![Capture d'écran 2023-12-05 175550](https://github.com/christianbrodbeck/Eelbrain/assets/13418371/0c721f11-d4c3-4692-abc1-2dddf5c56d13)
