### ISSUE TITLE
The math under TTestRelated

### ISSUE THREAD

**Issue by gurasog** [Eelbrain/Eelbrain#64]
Hey!

We are activate using the eelbrain library for our studies in EEG+language. We faced a problem with the statistical analysis, so I have a question.
Could you please tell me what do we actually do under the TTestRelated?

For example, I am checking the difference between correlations of two models. One model uses only word onset as a predictor and the second one uses two predictors (onset + SD).

```
tests['r_compare_onset+SD'] = eelbrain.testnd.TTestRelated(model_fits['onset'], model_fits['onset+SD'], 
                                                                       tfce=True, samples=1000, tail=1)

```
In model_fits['onset+SD'] I have correlation values.
![telegram-cloud-photo-size-2-5440386223341429049-x](https://github.com/christianbrodbeck/Eelbrain/assets/24228468/6c138a1e-04e6-4ba1-b6ce-c560f44bcba5)

I would like to know what do we actually permute here.

Thanks!

**Comment by christianbrodbeck** [comment]
Does that address this? https://github.com/christianbrodbeck/Eelbrain/commit/d93feb40755579ceb6cc66fb2d4ddc2762a95dc7
