### ISSUE TITLE
Improve documentation and/or GitHub readme

### ISSUE THREAD

**Issue by skjerns** [Eelbrain/Eelbrain#70]
Heyho!

I just stumbled across this repo and on first sight it looks promising and useful! However, I struggled quite a bit to get a good overview to what eelbrain actually offers to me. Maybe some short overview and/or summary on the GitHub readme would be useful? There's bits and pieces of that in the readthedocs and a lot of info in the publication, but nothing concise.

Eg What actually is eelbrain? What can and can't it do? What could you use it for?

Not everyone wants to read the publication to figure that out.

**Comment by christianbrodbeck** [comment]
Hi @skjerns, thanks for your suggestion. Would something like the three bullet points added [here](https://eelbrain.readthedocs.io/en/doc-test/index.html) at the top of the page serve the purpose you had in mind? 

@proloyd do you have additional thoughts?

**Comment by skjerns** [comment]
To me this reads slightly vague, some additions eg

- which data is eelbrain targeted at (as far as I can read it, you work mostly with m/eeg from continuous speech with it?)
- is there preprocessing in the pipeline included? what does it do?

**Comment by christianbrodbeck** [comment]
[Updated](https://eelbrain.readthedocs.io/en/doc-test/index.html)

> which data is eelbrain targeted at (as far as I can read it, you work mostly with m/eeg from continuous speech with it?)

I do, but these functions are agnostic to the content of the experiment. Any way to make this clearer?

> is there preprocessing in the pipeline included? what does it do?

I added a link to the pipeline intro itself, anything you would want to see further clarified?

**Comment by skjerns** [comment]
> I do, but these functions are agnostic to the content of the experiment. Any way to make this clearer?

fair enough! 

> I added a link to the pipeline intro itself, anything you would want to see further clarified?

that's better, yes! :)

**Comment by christianbrodbeck** [comment]
Thanks again for bringing this up!
